### ISSUE TITLE
Questions about encoding and decoding

### ISSUE THREAD

**Issue by zbbhhb** [Onixaz/picamera-h264-web-streaming#1]
I'm wondering, in this program, is coding done on the Raspberry Pi or WebSockets server? And where is the decoding done? If possible, can you explain it with a data flow chart? Thank you！

**Comment by Onixaz** [comment]
Encoding is done on Raspberry Pi's GPU.  These hardware encoded h264 frames are then transmitted to the client via Websockets and then decoded on the client's web browser with the help of Javascript decoder. 

Hope that answers your question :)

**Comment by zbbhhb** [comment]
Thank you for your reply. It has helped me a lot. I am currently learning the live streaming of the Raspberry Pi through your code. There was a problem when applying your code. As shown in the figure below, a lot of spaces suddenly appeared between the printed IP addresses. thank you！

![image](https://user-images.githubusercontent.com/47469906/78222691-3a79e580-74f8-11ea-9025-2d5c0eeca06b.png)

**Comment by Onixaz** [comment]
That's interesting.  What's the purpose of that sh script? Are you seeing the same output when you run "python server.py"?

**Comment by zbbhhb** [comment]
There is no problem in running server.py, but after I added a command to recognize keyboard input signal above the red line in the picture, and if ch == 'o', star video streaming. After running, it printed many spaces between IP address. I have studied your code carefully and found that it is not about these output IP address. I would like to ask how to delete these spaces or delete these IP addresses?

thank u!

![image](https://user-images.githubusercontent.com/47469906/78327101-a585f380-75ae-11ea-83a0-c02f922c5cd0.png)

**Comment by Onixaz** [comment]
To stop IP addresses from appearing in a terminal, you can simply overwrite the `log_message` method of `BaseHTTPRequestHandler`. 

Example here:
[https://stackoverflow.com/questions/3389305/how-to-silent-quiet-httpserver-and-basichttprequesthandlers-stderr-output](https://stackoverflow.com/questions/3389305/how-to-silent-quiet-httpserver-and-basichttprequesthandlers-stderr-output)
