### ISSUE TITLE
Using the frames

### ISSUE THREAD

**Issue by sk-t3ch** [Onixaz/picamera-h264-web-streaming#2]
Hey, I have been searching for a fast RaspberryPi camera stream web server and this appears to work really well.
I am attempting to process frames to add annotations using opencv, however I am unable to read the frames.

The code looks something like:

```
class BroadcastThread(Thread):
    def __init__(self, camera, output, websocket_server):
        super(BroadcastThread, self).__init__()
        self.camera = camera
        self.output = output
        self.websocket_server = websocket_server

    def run(self):
        try:
            self.camera.start_recording(self.output, 'h264', profile="baseline")
            while True:
                with self.output.condition:
                    self.output.condition.wait()
                    frame = self.output.frame
                    img = Image.open(BytesIO(frame))
```

and a frame looks like
```
FRAME:  b"\x00\x00\x00\x01!\x9ad\x02\x9d\xad\x1e\xf9\xbd\x83\xf1{\xef\xc4\xbc\xcb\x89\x9b\xdf\xd5\xfaj\xf1\xfd\xfbj\xa6\xf7^i\xdb\xe4\xc7\x15\xaec;\xfe\xe2\xed\xcd\x18n\xcb\xc8h\xba\xf5/\xb9;\xb3\xf7\xd9\xbd\x9a\xc4\x04\xeb\xfa\xd9D\xff.\xd6'\xd5\xe5\xb2\x8b\xf7\xdf7\xaa\xe9?\xb1\x9d\xfd\xef\xd9\t,\x8eno}\xfa\x89\xa3y\xe4\xdd>N\xf1+N;pG\xcb\xbe[\xcbE\xac\x91\x93c\xb3k\xf9\xbe\xe1\r\xc2\x17\xbf\x9b\xff\xf3\xc9\x9f\x1b\x93\xbc\xfb}\xe5\xeb_%\x9f5\xe6\xea\xd2wk\x92mr{\xf2M6\xa6\xcd\xdd\x1f\xf7\xd8\x1c\xbdZN\xaf\\\xd7\xe4\x93\xfc"
```

Is this a limitation of h264?

**Comment by Onixaz** [comment]
Hey,

Not necessarily a limitation of h264, but capturing individual frames with OpenCV, preprocessing them, and converting them back to h264 format will slow down streaming considerably. Especially on RPi CPU. So I advise you to look into https://github.com/Onixaz/Flask-Coral-Edge-TPU/blob/master/webstreaming.py repo if you want to preprocess frames before sending them to a browser.

**Comment by sk-t3ch** [comment]
Thank you so much, that example suits my needs much better!
